name: uni_calendar_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    ffi: ^2.1.3
    flutter:
        sdk: flutter
    intl: ^0.20.2
    json: ^0.20.4
    path: ^1.9.0
    path_provider: ^2.1.5
    sqflite: ^2.4.1
    sqflite_common_ffi: ^2.3.4+4
    url_launcher: ^6.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/db.json
